server:
  servlet:
    context-path: /catelog
      port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category
    username: root
    password: zafar
    driver-class-name:  com.mysql.jdbc.Driver
    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
